#!/usr/bin/env node

// Get version from git describe
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
  // Get git describe output (e.g., v1.0.0-5-g3a4b5c6)
  const version = execSync('git describe --dirty --long --always --match "v*"', { encoding: 'utf-8' }).trim();
  // If no tags exist, fallback to short commit hash
  const fallbackVersion = version || execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
  // Get commit date
  const commitDate = execSync('git log -1 --format=%cd --date=short', { encoding: 'utf-8' }).trim();
  // Create version info object
  const versionInfo = {
    version: fallbackVersion,
    commitDate,
    buildDate: new Date().toISOString(),
  };

  // Write to a TypeScript file
  const outputPath = path.join(__dirname, '../src/version.ts');
  const content = `// Auto-generated by scripts/get-version.js
// Do not edit manually

export const VERSION_INFO = ${JSON.stringify(versionInfo, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, content);
  console.log('✅ Version info generated:', versionInfo.version);
} catch (error) {
  console.error('❌ Error getting version:', error.message);
  // Create fallback version
  const fallbackContent = `// Auto-generated fallback version
export const VERSION_INFO = {
  version: 'dev',
  commitDate: 'unknown',
  buildDate: '${new Date().toISOString()}',
} as const;
`;
  fs.writeFileSync(path.join(__dirname, '../src/version.ts'), fallbackContent);
  console.log('⚠️  Using fallback version');
}
